# https://embarkstudios.github.io/cargo-deny/

[advisories]
unmaintained = "workspace"
ignore = []

[bans]
multiple-versions = "deny"
deny = []
skip = []
skip-tree = []

[licenses]
allow = ["MIT", "Apache-2.0"]
